# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-04 14:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(default='', max_length=13, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='副标题')),
                ('pages', models.IntegerField(blank=True, verbose_name='页数')),
                ('author', models.CharField(max_length=60, verbose_name='作者')),
                ('translator', models.CharField(blank=True, max_length=60, verbose_name='译者')),
                ('price', models.CharField(blank=True, max_length=60, verbose_name='价格')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='出版社')),
                ('pubdate', models.CharField(blank=True, max_length=60, verbose_name='出版日期')),
                ('cover_img', models.URLField(blank=True, verbose_name='封面图')),
                ('summary', models.TextField(blank=True, max_length=2000, verbose_name='内容简介')),
                ('author_intro', models.TextField(blank=True, max_length=2000, verbose_name='作者简介')),
                ('category', models.CharField(max_length=128, verbose_name='类别')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
            },
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='image/%Y/%m/%d/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Book')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=16)),
                ('permission', models.IntegerField(default=1)),
                ('contact', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
