# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-04 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20160112_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='contact',
            field=models.IntegerField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='image/%Y/%m/%d/'),
        ),
    ]
